stages:
  data_ingestion:
    cmd: python .\src\data\data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_processing:
    cmd: python src/data/data_processing.py
    deps:
    - data/raw
    - src/data/data_processing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/interim
    - src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/processed
    - models/vectorizer.pkl
  model_training:
    cmd: python src/models/model_training.py
    deps:
    - data/processed
    - src/models/model_training.py
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - models/model.pkl
    - src/models/model_evaluation.py
    metrics:
    - reports/metrics.json
  model_registration:
    cmd: python src/models/model_registration.py
    deps:
    - models/model.pkl
    - src/models/model_registration.py
