stages:
  data_ingestion:
    cmd: python .\src\data\data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_processing:
    cmd: python src/data/data_processing.py
    deps:
    - data/raw
    - src/data/data_processing.py
    outs:
    - data/interim
