name: CI


on: push

jobs:
  Project-test:

    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.18'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          dvc repro
      
      - name: Run Model Testing
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m unittest tests/test_model.py

      - name: Promote Model to Production
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: python scripts/promote_model.py
      
      - name: Running Flask Tests
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: python -m unittest tests/test_flask_app.py
      
      - name: login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 637423429951.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t abhayx-mlops .

      - name: Tag Docker Image
        run: |
          docker tag abhayx-mlops:latest 637423429951.dkr.ecr.eu-north-1.amazonaws.com/abhayx-mlops:latest

      - name: Push Docker Image to AWS ECR
        run: |
          docker push 637423429951.dkr.ecr.eu-north-1.amazonaws.com/abhayx-mlops:latest

                - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region ap-southeast-2
            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 637423429951.dkr.ecr.eu-north-1.amazonaws.com
            docker pull 637423429951.dkr.ecr.eu-north-1.amazonaws.com/abhayx-mlops:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 80:5000 -e DAGSHUB_PAT=${{ secrets.DAGSHUB_PAT }} --name mlops-app 637423429951.dkr.ecr.eu-north-1.amazonaws.com/abhayx-mlops:latest


      